# Copyright 2017-2021 ForgeFlow, S.L.
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).

{
    "name": "Stock Request",
    "summary": "Internal request for stock",
    "version": "18.0.1.0.0",
    "license": "LGPL-3",
    "website": "https://github.com/OCA/stock-logistics-request",
    "author": "ForgeFlow, Odoo Community Association (OCA)",
    "maintainers": ["LoisRForgeFlow", "etobella"],
    "category": "Warehouse Management",
    "depends": ["stock", "purchase", "contacts", "stock_outbouding_operation","stock_gl_account", "stock_3dbase",
                "gulfco_contact_registration_custom"],
    "data": [
        "security/stock_request_security.xml",
        "security/stockkeeper_security.xml",
        "security/ir.model.access.csv",
        'data/decimal_precision.xml',
        "views/product.xml",
        "views/delivery_for_recycling_request.xml",
        "views/select_multi_product_stock.xml",
        "views/stock_route_views.xml",
        "views/stock_request_views.xml",
        "views/stock_request_allocation_views.xml",
        "views/stock_move_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_request_order_views.xml",
        "views/res_config_settings_views.xml",
        "views/stock_request_menu.xml",
        "views/stock_request_order_view_inherit.xml",
        "views/stock_request_approvel_view.xml",
        "views/stock_is_claimable.xml",
        "views/stock_request_approval_workflow_views.xml",
        "data/stock_request_sequence_data.xml",
        "views/stock_scrap_views.xml",
        "views/stock_takeover_reason_view.xml",
        "views/account_account_view.xml",
        "views/stock_valuation_layer_views.xml",

    ],
    "pre_init_hook": "_pre_init_hook",
    "installable": True,
}
