{
    'name': 'Accounting PDC Management',
    'summary': 'Allow use PDC',
    'maintainer': 'Abdalla Mohamed',
    'author': "Plennix Technologies",
    'website': "https://www.plennix.com",
    'version': '18.0.1.1.1',
    'category': 'Accounting/Accounting',
    'license': 'OPL-1',
    'depends': ['base',
                'account',
                'promate_payment_custom_seq',
                # to appear custom sequence as display name.
                'gulfco_customer_customized_data'
                ],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/account_payment_register.xml',
        #'wizard/account_payment_cash.xml',
        'wizard/account_payment_recheque.xml',
        'wizard/account_payment_pdc_writeoff.xml',
        'wizard/account_payment_pdc_collection_fees.xml',
        'wizard/account_hand_over_reject.xml',
        'wizard/account_payment_pdc_collect.xml',
        'wizard/account_payment_pdc_bounce.xml',
        'wizard/account_payment_pdc_payable_clear.xml',
        'views/cheque_cancel_reason.xml',
        'views/account_journal.xml',
        'views/account_hand_over_pdc.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/account_deposit_pdc.xml',
        'views/res_config_settings.xml',
        'data/ir_sequence.xml',
        'data/mail_template.xml',
        'data/ir_config_parameter.xml',
        'data/ir_cron.xml',
        'wizard/account_payment_pdc_payable_delivered.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
