from . import crm_team
from . import customer_mapping
from . import fsm_order
from . import sale_order
from . import rma
from . import customer_channel
from . import res_partner
from . import fieldservice_team_password
from . import fsm_team
