{
    'name': 'Accounting CDC Management',
    'summary': 'Allow use CDC',
    'maintainer': '',
    'author': "",
    'website': "",
    'version': '18.0.1.1.1',
    'category': 'Accounting/Accounting',
    'license': 'OPL-1',
    'depends': ['account_pdc','account_check_printing'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/account_payment_register.xml',
        'wizard/account_payment_cash.xml',
        #'wizard/account_payment_recheque.xml',
        'wizard/refusal_reason_wizard_view.xml',
        'wizard/account_payment_cdc_writeoff.xml',
        'wizard/account_payment_cdc_collection_fees.xml',
        'wizard/account_hand_over_reject.xml',
        'wizard/account_payment_cdc_collect.xml',
        'wizard/account_payment_cdc_bounce.xml',
        'wizard/account_payment_cdc_payable_clear.xml',
        'views/account_journal.xml',
        'views/account_hand_over_cdc.xml',
        'views/account_payment.xml',
        'views/account_move.xml',
        'views/account_deposit_cdc.xml',
        'data/ir_sequence.xml',
        #'data/mail_template.xml',
        #'data/ir_config_parameter.xml',
        'wizard/account_payment_cdc_payable_delivered.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
