from . import res_company
from . import res_partner
from . import res_config_settings
from . import product_supplierinfo
from . import stock_location
from . import demand_planning
from . import purchase_request_line
from . import purchase_request
from . import purchase_order_line