from . import account_tax
from . import promo_product_group
from . import promo_slab_rule
from . import loyalty_program
from . import sale_order
from . import account_move
from . import woker_journal
from . import sale_order_line_reward
from . import account_move_line_reward
from . import product_template
from . import product_product