# -*- coding: utf-8 -*-
{
    'name': 'Gulfco Account Payment Extended',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'Gulfco Account Payment Extended',
    'author': 'Plennix',
    'website': 'https://www.plennix.com/',
    'depends': ['account', 'account_cdc', 'fieldservice', 'plnx_gulfco_sales_commission', 'hr', 'advance_payment_sale_purchase', 'gulfco_cash_transaction_limit', 'gulfco_account_reports','account_accountant','plennix_payment_amount_in_local_currency'],
    'data': [
        'security/ir.model.access.csv',
        'security/res_group.xml',
        'data/ir_sequence.xml',
        'data/account_payment_method_data.xml',
        'data/ir_server_action.xml',
        'data/cron.xml',
        'data/import_data.xml',
        'wizard/pdc_cdc_wizard_view.xml',
        'wizard/account_payment_register.xml',
        'wizard/account_reconcile_wizard.xml',
        'wizard/account_move_line_import_wizard_view.xml',
        'wizard/account_payment_pdc_bounce_view.xml',
        'wizard/account_payment_cdc_bounce_view.xml',
        'wizard/unreconciled_statement_wizard_view.xml',
        'report/custodian_payment_report_view.xml',
        'report/custodian_payment_summery_report_view.xml',
        'report/payment_receipt_voucher_report.xml',
        'report/cheque_report.xml',
        'views/custodian_view.xml',
        'views/hr_employee_views.xml',
        'views/account_payment_method_views.xml',
        'views/account_payment_view.xml',
        'views/bank_rec_widget_views.xml',
        'views/account_journal_dashboard_view.xml',
        'views/account_payment_term_view.xml',
        'views/payment_transfer_views.xml',
        'views/fsm_order_views.xml',
        'views/account_journal.xml',
        'views/account_move_views.xml',
        'views/account_reconcile_views.xml',
        'views/res_partner.xml',
        'views/monthly_pdc_customer_report_view.xml',
        'views/account_bank_statement_views.xml',
        'views/cash_remittance_view.xml',
    ],
    'installable': True,
    'application': False,
    'assets': {
        'web.assets_backend': [
            'gulfco_account_payment_extended/static/src/js/payment_form_compiler.js',
            'gulfco_account_payment_extended/static/src/components/bank_reconcilliation/list.js',
            'gulfco_account_payment_extended/static/src/views/list/match_existing_entries_list_controller.xml',
            'gulfco_account_payment_extended/static/src/views/list/account_move_line_reconcile_list_renderer.xml',
            'gulfco_account_payment_extended/static/src/js/kanban.js',
            'gulfco_account_payment_extended/static/src/components/bank_reconcilliation/bank_rec_form.xml',
            'gulfco_account_payment_extended/static/src/js/move_line_list_reconcile.xml',
            'gulfco_account_payment_extended/static/src/js/move_line_list_reconcile.js',
            'gulfco_account_payment_extended/static/src/js/action_hide.js',
        ],
    },
}
