from . import customer_article
from . import product
from . import stock_package_type
from . import sale_order
from . import sale_order_line
from . import stock_pciking
from . import sale_order_discount
from . import account_move_line
from . import customer_specification
from . import res_partner
from . import account_tax